//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : LifeServer
//  @ File Name : GuideActivity.java
//  @ Date : 2016/5/31
//  @ Author : hjt
//
//



package com.hjt.lifeserver.view;


public class GuideActivity {
}
