//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : LifeServer
//  @ File Name : MainActivity.java
//  @ Date : 2016/5/31
//  @ Author : hjt
//
//


package com.hjt.lifeserver.view;

import android.os.Build;
import android.os.Bundle;
import android.view.WindowManager;

import com.hjt.lifeserver.R;
import com.zhy.autolayout.AutoLayoutActivity;

public class MainActivity extends AutoLayoutActivity{
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        //setImmersionStatus();
        setContentView(R.layout.activity_main);
    }

    private void setImmersionStatus() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
            // 透明状态栏
              getWindow().addFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_NAVIGATION);
            // 透明导航栏
		    //getWindow().addFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_NAVIGATION);
        }
    }
}
