//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : LifeServer
//  @ File Name : MyApplication.java
//  @ Date : 2016/5/31
//  @ Author : hjt
//
//



package com.hjt.lifeserver.app;


public class MyApplication {
	public String username;
	public String password;
}
