//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : LifeServer
//  @ File Name : NewsEntity.java
//  @ Date : 2016/5/31
//  @ Author : hjt
//
//



package com.hjt.lifeserver.entity;


public class NewsEntity {
}
