//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : LifeServer
//  @ File Name : MyBaseAdapter.java
//  @ Date : 2016/5/31
//  @ Author : hjt
//
//



package com.hjt.lifeserver.adapter;


import android.content.Context;
import android.view.LayoutInflater;
import android.widget.BaseAdapter;

import java.util.List;

public abstract class MyBaseAdapter<T> extends BaseAdapter{
	public LayoutInflater inflater;
	public Context mContext;
	public List<T> datas;
}
