//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : LifeServer
//  @ File Name : BitmapUtils.java
//  @ Date : 2016/5/31
//  @ Author : hjt
//
//



package com.hjt.lifeserver.util;


public class BitmapUtils {
}
